* task
** DONE NOI2007 CASH
   CLOSED: [2015-05-02 Sat 11:55] SCHEDULED: <2015-04-29 Wed 20:00>
   - State "DONE"       from "STARTED"    [2015-05-02 Sat 11:55]
** TODO NOI2005 瑰丽华尔兹 
   SCHEDULED: <2015-04-30 Thu 18:00>
** TODO SHOI 2008 poj3567
   SCHEDULED: <2015-04-30 Thu 20:00>
   
   
* summary 1D1D优化策略
**  决策单调优化
    f[i] = f[j] + w[j, i]形式
    决策单调。可以打表找规律看决策是否单调。典型hnoi2008 toys
    四边形不等式：w[i,j]+w[i + 1, j + 1] <= w[i + 1, j] + w[i + 1, j],则满足决策单调性。
    有时候不满足决策单调性，但是去掉完全不合法状态之后却可以满足。例如USACO的gold
    
** 单调队列优化
   f[i] = max(g[j]) + w[i]形式，其中单调。
   可见，如果j<k, g[j]<g[k], 则j可以直接不考虑，所以此时维护g单调减的队列即可。
   如 IOI2008 islands.这道题还是有些细节的，对于基环外向树的题目，要点如下：
*** 找环
    首先形成bfs树，发现有环，记pt，ph，然后选pt沿着pre走到跟，一路打时间戳；再从ph沿着pre走，就可以找到lca。pt，ph到lca的路径，加上pt-->ph就是基环了。
    
*** 易错点
    容易只考虑子树之间的dp值，而忽略子树内部的dp值。
    
** 斜率优化
   f[i] = min(a[i] * x[j] + b[i] * y[j])的形式
   －更好的理解：设P=f[i],则 y = (-a/b)x + P/b. 求满足要求的最小截距。
   或者通过各种转化，最优决策就是从无穷远朝原点移动，第一个碰上的点为最优决策点。
   －很好的性质：所有最优决策一定在当前所有点构成的凸包上。（例如，在最优决策点划一条相应斜率的线，其余点均在该线上方，）
*** case1: 斜率以及x维均有单调性。         
    想像斜率越来越大的直线往y正方向移动，第i次移动首次碰上k。对于以后的
    决策，因为斜率更大，那么在k之前，第i次移动没有碰上的点必然再也用不上了，
    所以可以维护一个单调队列。
    －例如：hdu3507,把一个序列切开，每个部分权值是和平方加常数，求权值和最小值
*** case2: 什么限制都没有     
**** 平衡树解法
     这时候就没有了case1中的良好性质，为了便于理解，先说暴力作法：
     －询问的时候只需要二分找到斜率关系满足k1<k<k2的位置就可以找到最优转移点。
     －加入新点时，首先二分找到添加的位置。如果在凸包里边，什么都不
     用干；否则，往前往后找，边找边删。
     下面介绍正解：
     以x作为关键字构件平衡树，维护一个凸包序列，这个序列斜率随着x增大而
     增大（减小）。这时候，一个点一个点地添加，将会有如下操作:
***** 找最优决策点。
      这时候，因为以x为关键字，实际上也是以斜率为关键字。只需要根据斜率关系往左
      走，或者往右走，就可以在logN的复杂度内完成。
      
***** 添加点，维护凸包
      先logN找到应当插入的位置，判断是否需要加入这个点。如果需要，那么将相应
      点旋转到根，然后找到插入位置的前后点，再一路维护凸包前后删，最后再加入就行了。
      
**** cdq分治解法
     从例题cash来看。

**** 相应例题
***** NOI2007 CASH
      f[i]表示第i天手上的券全换成现金最多多少。
      f[i] = max(max(A[i] * x[j] + B[i] * x[j], f[j]))
      其中x[j],y[j]分别表示用f[j]的钱换成A，B券分别能有多少。
      就是经典的斜率优化问题咯。不用平衡树的话可以离线用cdq分治。先按照－A[i]/B[i]排序（具体大小顺序画一画就知道了）。
      solve(l, r)时需要按照下标lab大小分为两部分。然后solve(l,mid),同时主义归并把递散维x排好序。l～mid至mid＋1~r的转移就转化称乐case1.
      最后solve(mid + 1, r)，接着归并排好x就行了。
****** 排序的顺序，凸壳的方向错了。写之前一定要画清楚。
****** 这里归并排一维的序可以节省一个log的复杂度
****** cdq分治的顺序至关重要，千万不能乱。
***** NOI2005 瑰丽华尔兹

      
      
